apiVersion: v1alpha1

static:
  - name: ec2-i-0fb5c3f5782d807f0
    regions:
      - eu-north-1
    namespace: AWS/EC2
    dimensions:
      - name: InstanceId
        value: i-0fb5c3f5782d807f0
    metrics:
      - name: CPUUtilization
        statistics:
          - Average
          - Maximum
        period: 300
        length: 3600
      - name: NetworkIn
        statistics:
          - Average
        period: 300
        length: 3600
      - name: NetworkOut
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskReadBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskWriteBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: StatusCheckFailed
        statistics:
          - Maximum
        period: 300
        length: 3600

  - name: ec2-i-07a68bb7066c97e64
    regions:
      - ap-south-1
    namespace: AWS/EC2
    dimensions:
      - name: InstanceId
        value: i-07a68bb7066c97e64
    metrics:
      - name: CPUUtilization
        statistics:
          - Average
          - Maximum
        period: 300
        length: 3600
      - name: NetworkIn
        statistics:
          - Average
        period: 300
        length: 3600
      - name: NetworkOut
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskReadBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskWriteBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: StatusCheckFailed
        statistics:
          - Maximum
        period: 300
        length: 3600

  - name: ec2-i-0495082984c755da5
    regions:
      - ap-south-2
    namespace: AWS/EC2
    dimensions:
      - name: InstanceId
        value: i-0495082984c755da5
    metrics:
      - name: CPUUtilization
        statistics:
          - Average
          - Maximum
        period: 300
        length: 3600
      - name: NetworkIn
        statistics:
          - Average
        period: 300
        length: 3600
      - name: NetworkOut
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskReadBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskWriteBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: StatusCheckFailed
        statistics:
          - Maximum
        period: 300
        length: 3600
  
  - name: ec2-i-074ca6ca35546b58b
    regions:
      - ap-southeast-1
    namespace: AWS/EC2
    dimensions:
      - name: InstanceId
        value: i-074ca6ca35546b58b
    metrics:
      - name: CPUUtilization
        statistics:
          - Average
          - Maximum
        period: 300
        length: 3600
      - name: NetworkIn
        statistics:
          - Average
        period: 300
        length: 3600
      - name: NetworkOut
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskReadBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskWriteBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: StatusCheckFailed
        statistics:
          - Maximum
        period: 300
        length: 3600

  - name: ec2-i-0987654321abcdef0
    regions:
      - us-east-1
    namespace: AWS/EC2
    dimensions:
      - name: InstanceId
        value: i-0987654321abcdef0
    metrics:
      - name: CPUUtilization
        statistics:
          - Average
          - Maximum
        period: 300
        length: 3600
      - name: NetworkIn
        statistics:
          - Average
        period: 300
        length: 3600
      - name: NetworkOut
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskReadBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: DiskWriteBytes
        statistics:
          - Average
        period: 300
        length: 3600
      - name: StatusCheckFailed
        statistics:
          - Maximum
        period: 300
        length: 3600
